### ISSUE TITLE
Comparision against nnUNet

### ISSUE THREAD

**Issue by chris-clem** [UCSC-VLAA/SwinMM#1]
Thank you for making your nice work public!

I was just wondering whether you compared your method against nnUNet (https://github.com/MIC-DKFZ/nnUNet) as well? It performs best in the WORD paper (https://arxiv.org/pdf/2111.02403.pdf).

**Comment by yuyinzhou** [comment]
We appreciate your interest in our research! Our technique focuses on enhancing the self-supervised learning pipeline with Transformers, and doesn't directly compare with the fully-supervised nn-UNet. According to https://arxiv.org/pdf/2111.02403.pdf, our method might perform slightly lower than nn-UNet (86+% vs. 87+%). However, we are optimistic about the prospects of integrating our method with nn-UNet, as it could potentially yield improved performance.

**Comment by chris-clem** [comment]
Thank you for your quick answer! It would be nice to integrate self-supervised learning into nn-UNet. It is still a very good baseline.
