### ISSUE TITLE
WORD checkpoint points to pretrained_checkpoint

### ISSUE THREAD

**Issue by thangngoc89** [UCSC-VLAA/SwinMM#2]
On the README, [WORD_finetuned_ckpt.pt](https://drive.google.com/file/d/1VFT1Oz5UGjAaXLdWAAdeD0mVeLyCQ0ry/view?usp=sharing) pointed to the same checkpoint as pretrained_ckpt.pt
Can you please update it? 

Thank you

**Comment by yuyinzhou** [comment]
Thanks for bringing up this issue. We have now updated the checkpoint link. If you come across any additional issues, please don't hesitate to inform us.

**Comment by thangngoc89** [comment]
Thank you very much.
