### ISSUE TITLE
about acdc

### ISSUE THREAD

**Issue by AustinYuAo** [UCSC-VLAA/SwinMM#7]
Disturbed the author! 
Thank you for making your code public. Can you introduce the preprocessing process of the ACDC dataset?

**Comment by yqwang01** [comment]
Thank you for your question. 
The ACDC MRI images are interpolated to the isotropic voxel spacing of 1.0 mm and normalized into zero to one. We sample the training sub-volumes of 64^64^64 voxels by ratio of positive and negative as 2:1. Augmentation probabilities for random flip, rotation, intensities scaling and shifting are set to 0.5, 0.1, 0.2, 0.5, respectively.

**Comment by AustinYuAo** [comment]
Thank you for your quick reply！The ACDC dataset has a very small number of slices in the Z direction. Is it necessary to add spatial padding for the preprocessing of the ACDC dataset?

**Comment by yqwang01** [comment]
You don't need to do spatial padding. Remember to interpolate the volume so that the spacing is isotropic. You can change the crop size if needed.
